# Paste your MongoDB Connection String here
mongo_uri = "mongodb+srv://shashank92:YrlBh8cR5Xc4Y8xl@cluster0.efjm55y.mongodb.net/?appName=Cluster0"

# Paste your Random Secret here, this below generated by running "openssl rend -hex 32"
jwt_secret = "e6c55b2c19eadd30345f985cde2af973bd8c2f01f15061acdaab2c77577e3ff4"

# Paste your Slack Webhook URL here
sender_email_address = "shashank9928@gmail.com"

# your ip
my_ip = "YOUR_PUBLIC_IP_CIDR"
