// ==========================================
// PERSONAL BOOK APPLICATION - BACKEND SERVER
// ==========================================

const express = require('express');
const { Sequelize, DataTypes, Op } = require('sequelize'); // 🔑 Import Sequelize
const cors = require('cors');
const jwt = require('jsonwebtoken');
const path = require('path');
const { randomUUID } = require('crypto');

// --- CONFIGURATION SECTION ---
const PORT = process.env.PORT || 5000;
// 🔑 UPDATED: Use the new environment variable name DATABASE_URL
const DATABASE_URL = process.env.DATABASE_URL;
const JWT_SECRET = process.env.JWT_SECRET;
const AWS_REGION = process.env.AWS_REGION || "us-west-2";

const SENDER_EMAIL_ADDRESS = process.env.SENDER_EMAIL_ADDRESS; 

// Initial Master Admin Credentials
const INITIAL_MASTER_EMAIL = "shashank@gmail.com";
const INITIAL_MASTER_PASS = "admin123";

const app = express();

app.use(cors());
app.use(express.json());

// -------------------------------------------------------------
// 🔑 POSTGRESQL/SEQUELIZE CONNECTION SETUP
// -------------------------------------------------------------

// Initialize Sequelize using the connection string from Secrets Manager
const sequelize = new Sequelize(DATABASE_URL, {
    dialect: 'postgres',
    protocol: 'postgres',
    dialectOptions: {
        // Since RDS is inside your private VPC, SSL is often not required 
        // or explicitly handled, but keeping it open for robust cloud connection.
        ssl: false,
    },
    logging: false, // Set to true to see SQL queries in logs
});

// -------------------------------------------------------------
// 🔑 SEQUELIZE DATA MODELS (Replacing Mongoose Schemas)
// -------------------------------------------------------------

// Function to convert complex Mongoose Schemas to Sequelize Models
const User = sequelize.define('User', {
    // Primary Key is auto-generated by Sequelize by default (id)

    username: { type: DataTypes.STRING, allowNull: false },
    email: { type: DataTypes.STRING, allowNull: false, unique: true },
    password: { type: DataTypes.STRING }, // Still required, but handling is simpler
    secretId: { type: DataTypes.STRING, unique: true }, // The user's login ID
    role: { 
        type: DataTypes.ENUM('master', 'user'), 
        defaultValue: 'user' 
    },
    registeredAt: { 
        type: DataTypes.STRING, 
        defaultValue: () => new Date().toLocaleString() 
    }
}, {
    tableName: 'users', // Define table name explicitly
    timestamps: false   // Disable default Sequelize timestamps (createdAt/updatedAt)
});


const Profile = sequelize.define('Profile', {
    // Primary Key is auto-generated by Sequelize by default (id)

    // Foreign Key to the User (using secretId as the logical link, 
    // although this isn't a true Sequelize foreign key relationship here for simplicity)
    userId: { type: DataTypes.STRING, allowNull: false, unique: true }, 
    
    publicLinkKey: { type: DataTypes.UUID, unique: true, defaultValue: Sequelize.literal('uuid_generate_v4()') },

    // 🔑 Mongoose's nested objects and arrays are replaced with the JSONB datatype
    about: { 
        type: DataTypes.JSONB, 
        defaultValue: { name: "New User", bio: "Bio goes here...", image: "https://api.dicebear.com/7.x/avataaars/svg?seed=New" }
    },
    education: { type: DataTypes.JSONB, defaultValue: [] },
    learnings: { type: DataTypes.JSONB, defaultValue: [] },
    projects: { type: DataTypes.JSONB, defaultValue: [] },
    interests: { type: DataTypes.JSONB, defaultValue: [] },
    wishlist: { type: DataTypes.JSONB, defaultValue: [] },
    tours: { type: DataTypes.JSONB, defaultValue: [] },
    bestPics: { type: DataTypes.JSONB, defaultValue: [] },

}, {
    tableName: 'profiles', // Define table name explicitly
    timestamps: false
});

// --- UTILS ---
// 🔑 REWRITTEN: Using Sequelize findOne and create
const seedMasterAdmin = async () => {
    try {
        // Check if master admin exists (Sequelize findOne syntax)
        const adminExists = await User.findOne({ where: { role: 'master' } });
        
        if (!adminExists) {
            // Create a new User (Sequelize create syntax)
            const newAdmin = await User.create({
                username: "Master Admin",
                email: INITIAL_MASTER_EMAIL,
                password: INITIAL_MASTER_PASS,
                role: 'master',
                secretId: "MASTER"
            });
            console.log(`👑 Master Admin created`);
        }
    } catch (err) {
        console.error("Seed Admin Error:", err.message);
    }
};

const sendRegistrationNotification = (username, secretId) => {
    console.log(`✉️ SUCCESS: User ${username} registered. Admin must provide Secret ID: ${secretId} to the user.`);
};


// --- MIDDLEWARE ---
const authenticateToken = (req, res, next) => {
    const authHeader = req.headers['authorization'];
    const token = authHeader && authHeader.split(' ')[1];
    if (!token) return res.sendStatus(401);
    jwt.verify(token, JWT_SECRET, (err, user) => {
        if (err) return res.sendStatus(403);
        req.user = user;
        next();
    });
};

// --- ROUTES ---

// 1. LOGIN
app.post('/api/auth/login', async (req, res) => {
    const { email, password, secretId, type } = req.body;
    try {
        let user;
        if (type === 'master') {
            // 🔑 REWRITTEN: Sequelize findOne with multiple conditions
            user = await User.findOne({ where: { email, role: 'master' } });
            
            if (!user || user.password !== password) return res.status(401).json({ message: 'Invalid Admin Credentials' });
            
            // Sequelize model instances use .dataValues to access properties, though direct access often works.
            const token = jwt.sign({ role: 'master', id: user.id, username: user.username }, JWT_SECRET);
            return res.json({ token, role: 'master', username: user.username });
        } else {
            // 🔑 REWRITTEN: Sequelize findOne with multiple conditions
            user = await User.findOne({ where: { email, secretId, role: 'user' } });

            if (!user) return res.status(401).json({ message: 'Invalid Email or User ID' });
            
            const token = jwt.sign({ role: 'user', id: user.secretId, username: user.username }, JWT_SECRET);
            return res.json({ token, role: 'user', username: user.username, id: user.secretId });
        }
    } catch (err) {
        res.status(500).json({ message: 'Server Error: ' + err.message });
    }
});

// 2a. GET ALL NON-MASTER USERS (ADMIN PANEL)
app.get('/api/users/list', authenticateToken, async (req, res) => {
    if (req.user.role !== 'master') {
        return res.status(403).json({ error: 'Forbidden. Master Admin access required.' });
    }

    try {
        // 🔑 REWRITTEN: Sequelize findAll with attributes selection
        const users = await User.findAll({ 
            where: { role: 'user' },
            attributes: ['username', 'email', 'secretId', 'role', 'registeredAt']
        });
        res.status(200).json(users);
    } catch (err) {
        console.error('Error fetching user list:', err);
        res.status(500).json({ error: 'Failed to retrieve user list.' });
    }
});


// 3. REGISTER NEW USER
app.post('/api/users/register', authenticateToken, async (req, res) => {
    if (req.user.role !== 'master') return res.sendStatus(403);

    const { username, email } = req.body;
    const newId = Math.floor(100000 + Math.random() * 900000).toString();

    try {
        // 🔑 REWRITTEN: Sequelize create for User
        const newUser = await User.create({ username, email, secretId: newId, role: 'user' });

        // 🚨 MODIFIED: Generate the Public Link Key (PLK) here
        const newPublicLinkKey = randomUUID();

        // 🔑 REWRITTEN: Sequelize create for Profile
        const defaultProfile = await Profile.create({
            userId: newId,
            // JSONB data is passed as a standard JS object
            about: { name: username, bio: "Bio goes here...", image: "https://api.dicebear.com/7.x/avataaars/svg?seed=New" },
            publicLinkKey: newPublicLinkKey, // Store the generated UUID
        });

        sendRegistrationNotification(username, newId);
        
        res.status(201).json(newUser);
    } catch (err) {
        console.error("User registration error:", err.message);
        // 🔑 REWRITTEN: Sequelize unique constraint error check
        // Unique constraint error check is done via the name 'SequelizeUniqueConstraintError'
        if (err.name === 'SequelizeUniqueConstraintError') {
             // Extract the field that caused the unique constraint failure
             const field = err.errors[0].path; 
             return res.status(409).json({ error: `Registration failed. ${field} already exists.` });
        }
        res.status(500).json({ error: "Registration failed due to server error." });
    }
});

// 4. DELETE USER
app.delete('/api/users/:secretId', authenticateToken, async (req, res) => {
    if (req.user.role !== 'master') return res.sendStatus(403);

    const { secretId } = req.params;

    try {
        // 🔑 REWRITTEN: Sequelize destroy for User and Profile
        const userResult = await User.destroy({ where: { secretId: secretId } });
        await Profile.destroy({ where: { userId: secretId } });

        if (userResult === 0) { // Sequelize destroy returns the number of rows affected
            return res.status(404).json({ error: `User with ID ${secretId} not found.` });
        }

        res.status(200).json({ message: `User with ID ${secretId} and profile deleted successfully.` });
    } catch (err) {
        console.error('Error deleting user:', err);
        res.status(500).json({ error: 'Failed to delete user and profile.' });
    }
});

// 5. PROFILE ROUTES (GET & PUT)
app.get('/api/profile/:userId', async (req, res) => {
    try {
        // 🔑 REWRITTEN: Sequelize findOne
        const profile = await Profile.findOne({ where: { userId: req.params.userId } });
        if (!profile) return res.status(404).json({ message: "Profile not found" });
        res.json(profile);
    } catch (err) { res.status(500).json({ error: err.message }); }
});

app.put('/api/profile/:userId', authenticateToken, async (req, res) => {
    if (req.user.role !== 'master' && req.user.id !== req.params.userId) return res.sendStatus(403);
    try {
        // 🔑 REWRITTEN: Sequelize update (returns [count, rows])
        await Profile.update(req.body, { 
            where: { userId: req.params.userId },
            returning: true // Returns the updated object
        });
        
        // Fetch the updated profile to return to the client
        const updatedProfile = await Profile.findOne({ where: { userId: req.params.userId } });
        res.json(updatedProfile);
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// 6. GET PUBLIC PROFILE BY SECRET ID (UNAUTHENTICATED)
app.get('/api/profile/public/:publicLinkKey', async (req, res) => {
    const { publicLinkKey } = req.params;

    try {
        // 1. Find the Profile using the publicLinkKey
        const profile = await Profile.findOne({ where: { publicLinkKey: publicLinkKey } });
        if (!profile) {
            return res.status(404).json({ error: 'Profile data not found.' });
        }

        // 2. Find the User using the Profile's userId (Secret ID)
        const user = await User.findOne({ 
            where: { secretId: profile.userId },
            attributes: ['username'] // Select only the username
        });
        if (!user) {
            return res.status(404).json({ error: 'Associated user not found.' });
        }

        // 3. Return combined public data
        const publicData = {
            username: user.username,
            profile: profile
        };

        res.status(200).json(publicData);

    } catch (err) {
        console.error('Error fetching public profile:', err);
        res.status(500).json({ error: 'Failed to retrieve public profile data.' });
    }
});


console.log("Trying to connect to PostgreSQL:", DATABASE_URL);

// -------------------------------------------------------------
// 🔑 SERVER STARTUP (REPLACING MONGOOSE CONNECTION)
// -------------------------------------------------------------
sequelize.authenticate()
    .then(() => {
        console.log('✅ Connection to PostgreSQL established.');
        
        // 🔑 CRITICAL: Sync models to database (creates tables if they don't exist)
        return sequelize.sync(); 
    })
    .then(() => {
        console.log('✅ PostgreSQL tables synchronized.');
        return seedMasterAdmin();
    })
    .then(() => {
        app.listen(PORT, () => console.log(`🚀 Server running on port ${PORT}`));
    })
    .catch(err => {
        console.error('❌ PostgreSQL connection or synchronization error:', err.message);
        // Important: Stop the process if the database connection fails
        process.exit(1);
    });
